---
title: 'Reproducible Research: Peer Assessment 2'
output: 
        html_document: 
                keep_md: true
---

# Reproducible Research: Peer Assessment 2: Storm Data Analysis

## Synopsis


## Requirements
```{r requirements}
require(dplyr)
require(ggplot2)
```

## Loading and Processing the Raw Data
### Fetching data
Data was originally fetched on 19 August 2015.
```{r fetching data}
BZ_FILE_NAME <- 'StormData.csv.bz2'

if (!file.exists(BZ_FILE_NAME)) {
        download.file(
                url = 'https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2',
                destfile = BZ_FILE_NAME,
                method = 'curl'
        )
}
```


### Load the data

```{r loading data }
bz_file <- bzfile(BZ_FILE_NAME)
storm_data <- tbl_df(read.csv(bz_file))
```

```{r health effects by event type}
by_evtype <- storm_data %>% 
        group_by(EVTYPE) %>%
        summarise(fatalaties = sum(FATALITIES), injuries = sum(INJURIES))
```

```{r}
evt_count <- dim(by_evtype)[1]
top_evtype <- by_evtype %>%
        filter(rank(fatalaties, ties.method='first') > (evt_count - 10) | rank(injuries, ties.method = 'first' ) > (evt_count - 10))
```

```{r}
ggplot(top_evtype) + 
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
        aes(x = reorder(EVTYPE, fatalaties), y = fatalaties) +
        geom_bar(stat = "identity") +
        geom_text(aes(label = fatalaties), vjust = 0) +
        xlab("Event Type") +
        ylab("Number of Fatalaties") +
        ggtitle("Most Fatal Events")
```

```{r}
top_evtype <- arrange(top_evtype, injuries)
ggplot(top_evtype) + 
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
        aes(x = reorder(EVTYPE, injuries), y = injuries) +
        geom_bar(stat = "identity") +
        geom_text(aes(label = injuries), vjust = 0) +
        xlab("Event Type") +
        ylab("Number of Injuries") +
        ggtitle("Most Injury-Causing Events")
```
